# Generated by Django 4.1 on 2022-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='acception',
            field=models.BooleanField(default=False),
        ),
    ]
